### ISSUE TITLE
money issue unturned rp

### ISSUE THREAD

**Issue by gschep18** [mycpphurts/HorizonNPC-IssueTracker#5]
Issue: Bank and atm are blank for me

NPC: all bank NPC's and atms

Expected result: I can buy it but it is not in my inventory when i buy and i physically can see the money when withdrawing it just how much it cost

Result obtained: Did not get my money
 Walk to the atm or bank teller and withdraw money, and no money is visible just the price

Media proof: 
![Screenshot 2024-07-01 200704](https://github.com/mycpphurts/HorizonNPC-IssueTracker/assets/174394187/f654cef9-7c11-46db-a0aa-df8f64672176)

**Comment by mycpphurts** [comment]
Hello,

I've seen and experienced this bug before.

This happens when the money mod doesn't load properly on client-side (your side). So, here are some steps to potentially fix this:

- Restart your game
- Verifying game files on Steam
- Deleting the 304930 folder in (Steam Location)/workshop/content

More information on fixes can be found [here](https://steamcommunity.com/sharedfiles/filedetails/?id=3006524866)

Closing this issue now. Any further issues related to this, feel free to report in bug-report or follow up and reopen the issue here!
